addpath('C:\Users\tsitsoka\Documents\YALMIP-master','C:\Users\tsitsoka\Documents\YALMIP-master\extras','C:\Users\tsitsoka\Documents\YALMIP-master\solvers',...
    'C:\Users\tsitsoka\Documents\YALMIP-master\modules\parametric','C:\Users\tsitsoka\Documents\YALMIP-master\modules\moment',...
    'C:\Users\tsitsoka\Documents\YALMIP-master\modules\global', 'C:\Users\tsitsoka\Documents\YALMIP-master\modules\sos','C:\Users\tsitsoka\Documents\YALMIP-master\operators',...
    'C:\Users\tsitsoka\Documents\YALMIP-master\modules');
savepath 